title: EcoTechThread
description: Um site sobre moda sustentável
baseurl: /EcoTechThread"
url: "https://Fleksz1.github.io"

theme: jekyll-theme-primer
plugins:
  - jekyll-feed

# Diretórios de origem e destino para o Jekyll
source: '.'
destination: './_site'

# Caminho do CSS
sass:
  style: compressed

css: "assets/css/style.css"  # Certifique-se de que esse caminho está correto
